version: "3.9" # versi schema docker-compose
services:
    lms_db_service:
        image: postgres:16
        container_name: LMS_DB_postgres_container
        restart: no
        environment:
            POSTGRES_USER: lmsdev
            POSTGRES_PASSWORD: lmsdev
            POSTGRES_DB: lmsdb
        ports:
            - "1414:5432"
        volumes:
            # - ./database/pgdata:/var/lib/postgresql/data
            - lmsdbdev_pgdata:/var/lib/postgresql/data

    minio:
        image: minio/minio:latest
        container_name: LMS_minio_container
        ports:
            - "9000:9000" # S3 API
            - "9090:9090" # Console (UI)
        environment:
            MINIO_ROOT_USER: lms_minio_dev # Ganti dengan user aman
            MINIO_ROOT_PASSWORD: lms_minio_dev # Ganti dengan password aman
        command: server /data --console-address ":9090"
        volumes:
            - ./storage/minio_data:/data
            # - ./storage/pdfs:/data/pdfs # opsional: mount folder host untuk PDF
        restart: unless-stopped

volumes:
    lmsdbdev_pgdata:
